#  Register assemblies for strong name verification skipping

$registryPath = "HKLM:\SOFTWARE\Microsoft\StrongName\Verification"
$publicKeyToken="31bf3856ad364e35"
$assemblies = "Microsoft.ServiceFabric.Common",
              "Microsoft.ServiceFabric.Client",
              "Microsoft.ServiceFabric.Client.Http"

Write-Host "Registering assemblies generated by this repository for strong name verification skipping."
foreach ($assembly in $assemblies)
{
    $assemblyIdentity = "$assembly,$publicKeyToken"
    New-Item -Path "$registryPath\$assemblyIdentity" -Force | Out-Null
}
